#!/bin/sh
if [ -z "${K8S_CONTEXT}" ]; then
    K8S_CONTEXT=gke_plasma-geode-127520_us-central1-a_jupyterlabdemo-lsst-codes
fi
ccl="cluster: ${K8S_CONTEXT}"
kubectl config view | \
    grep -A1 "${ccl}" | \
    grep namespace | \
    cut -d ':' -f 2 | \
    cut -d ' ' -f 2
